/*!
 * @file        bearertoken.hpp
 * @brief       This file is part of the Tegra System.
 * @details     Bearertoken interface for apis.
 * @author      <a href='https://www.kambizasadzadeh.com'>Kambiz Asadzadeh</a>
 * @package     The Genyleap
 * @since       29 Aug 2022
 * @copyright   Copyright (c) 2022 The Genyleap. All rights reserved.
 * @license     https://github.com/genyleap/tegra/blob/main/LICENSE.md
 *
 */

#ifndef TEGRA_BEARER_TOKEN_ABSTRACT_HPP
#define TEGRA_BEARER_TOKEN_ABSTRACT_HPP

//! Tegra's Common.
#ifdef __has_include
# if __has_include(<common>)
#   include <common>
#else
#   error "Tegra's common was not found!"
# endif
#endif

//! Tegra's Abstract Api.
#ifdef __has_include
# if __has_include(<abstracts/api>)
#   include <abstracts/api>
#else
#   error "Tegra's api was not found!"
# endif
#endif

TEGRA_NAMESPACE_BEGIN(Tegra::Abstracts::Apis)

/*!
 * \brief The AuthorizationInfo class
 */
struct AuthorizationInfo __tegra_final
{
    OptionalString token;  ///< The bearer token is a cryptic string.
};

/*!
 * \brief HTTP Bearer Authentication
 * Bearer authentication (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens.
 * The name “Bearer authentication” can be understood as “give access to the bearer of this token.” The bearer token is a cryptic string, usually generated by the server in response to a login request.
 */
class __tegra_export AbstractBearerToken : protected AbstractApi
{
public:
    TEGRA_DEFAULT_INTERFACE_OCTORS(AbstractBearerToken)

    /*!
     * \brief get function will gets output of access string.
     * \returns as final string.
     */
   __tegra_no_discard __tegra_virtual OptionalString get() __tegra_const_noexcept = __tegra_zero;

private:
    TEGRA_DISABLE_COPY(AbstractBearerToken)
};

TEGRA_NAMESPACE_END

#endif  // TEGRA_BEARER_TOKEN_ABSTRACT_HPP
